/*
    Sistema Experto #1 (Knowledge base module):
        medical_knowledge_base.pl
    Creado:
        May 21, 2018 13:49:37
    Dominio:
        Diagnóstico médico a través de la identificación de síntomas.
        Trata los sintomas como una lista multi-elementos.
*/

conocimiento('SARAMPION',
['EL PACIENTE ESTA CUBIERTO DE PUNTOS',
'EL PACIENTE TIENE TEMPERATURA ALTA',
'EL PACIENTE TIENE OJOS ROJOS',
'EL PACIENTE TIENE TOS SECA']).

conocimiento('INFLUENZA',
['EL PACIENTE TIENE DOLOR EN LAS ARTICULACIONES',
'EL PACIENTE TIENE MUCHO ESTORNUDO',
'EL PACIENTE TIENE DOLOR DE CABEZA']).

conocimiento('MALARIA',
['EL PACIENTE TIENE TEMPERATURA ALTA',
'EL PACIENTE TIENE DOLOR EN LAS ARTICULACIONES',
'EL PACIENTE TIEMBLA VIOLENTAMENTE',
'EL PACIENTE TIENE ESCALOFRIOS']).

conocimiento('GRIPE',
['EL PACIENTE TIENE CUERPO CORTADO',
'EL PACIENTE TIENE DOLOR DE CABEZA',
'EL PACIENTE TIENE TEMPERATURA ALTA']).

conocimiento('TIFOIDEA',
['EL PACIENTE TIENE FALTA DE APETITO',
'EL PACIENTE TIENE TEMPERATURA ALTA',
'EL PACIENTE TIENE DOLOR ABDOMINAL',
'EL PACIENTE TIENE DOLOR DE CABEZA',
'EL PACIENTE TIENE DIARREA']).