/*
    Sistema Experto #2 (Knowledge base module):
        garage_knowledge_base.pl
    Creado:
        May 21, 2018 17:25:51
    Dominio:
        Diagnóstico de problemas mecánicos en un automóvil a través de la identificación de síntomas.
        Trata los sintomas como una lista multi-elementos.
*/

conocimiento('BANDA DEL ALTERNADOR DEFECTUOSA',
['LA BANDA DEL ALTERNADOR TIENE GRIETAS',
'LA BANDA DEL ALTERNADOR ESTA CRISTALIZADA',
'LA BANDA DEL ALTERNADOR ESTA FLOJA']).

conocimiento('BANDA DEL ALTERNADOR DEFECTUOSA',
['LA BANDA DEL ALTERNADOR ESTA ENGRASADA',
'LA BANDA DEL ALTERNADOR RECHINA AL GIRAR']).

conocimiento('BATERIA DEFECTUOSA',
['LAS LUCES Y EL VENTILADOR ESTAN ENCENDIDOS',
'EL MOTOR ESTA APAGADO',
'LA BATERIA TIENE UN VOLTAJE MENOR A 10.5V']).

conocimiento('REGULADOR DEFECTUOSO',
['EL MOTOR ESTA EN MARCHA',
'LAS LUCES ESTAN ENCENDIDAS',
'LAS LUCES SE INTENSIFICAN AL ACELERAR']).

conocimiento('ALTERNADOR DEFECTUOSO',
['LA BATERIA ESTA EN BUENAS CONDICIONES FISICAS',
'LA LUZ DE ADVERTENCIA PERMANECE ENCENDIDA',
'EL MOTOR DE ARRANQUE GIRA LENTAMENTE']).

conocimiento('SISTEMA DE FRENOS DEFECTUOSO',
['EL PEDAL DEL FRENO ESTA DURO',
'AL FRENAR SE PRODUCE UN TIRO LATERAL',
'LAS RUEDAS RECHINAN AL FRENAR']).