/*
    Sistema Experto #4 (Knowledge base module):
        troubleshooting_knowledge_base.pl
    Creado:
        June 08, 2018 11:35:16
    Dominio:
        Diagnóstico de problemas técnicos en el hardware de una PC a través de la identificación de síntomas.
        Trata los sintomas como una lista multi-elementos.
*/

conocimiento('FALLA DE DISCO DURO',
['EL SISTEMA SE CUELGA O FALLA FRECUENTEMENTE Y DE FORMA IRREGULAR',
'APARECEN ERRORES CUANDO SE COPIAN ARCHIVOS',
'LOS NOMBRES DE ARCHIVOS Y CARPETAS SE CAMBIAN',
'LOS ARCHIVOS DESAPARECEN',
'LAS CARPETAS Y ARCHIVOS TARDAN EN ABRIRSE',
'EL DISCO DURO EMITE RUIDOS INUSUALES']).

conocimiento('FALLA DE MEMORIA RAM',
['EL SISTEMA SE REINICIA',
'EL SISTEMA TRABAJA LENTO',
'HAY PROGRAMAS QUE FALLAN DE MANERA ALEATORIA',
'ALGUNAS VENTANAS SE CIERRAN']).

conocimiento('FALLA EN TARJETA DE VIDEO',
['EL SISTEMA SE CUELGA O FALLA FRECUENTEMENTE Y DE FORMA IRREGULAR',
'EL SISTEMA SE REINICIA',
'APARECEN ZONAS DISTORSIONADAS EN LA IMAGEN',
'LA PANTALLA SE APAGA UNOS SEGUNDOS Y LUEGO REGRESA LA IMAGEN']).

conocimiento('FALLA EN PLACA BASE',
['EL EQUIPO ENCIENDE PERO NO TERMINA DE ARRANCAR',
'EL SISTEMA OPERATIVO NO CARGA',
'EL EQUIPO SE APAGA DE REPENTE',
'EL EQUIPO EMITE PITIDOS EN EL ARRANQUE',
'EL EQUIPO NO PASA EL POST SCREEN']).

conocimiento('MALWARE DE RED',
['EL NAVEGADOR WEB SE CUELGA O NO RESPONDE',
'LA PAGINA DE INICIO DEL NAVEGADOR WEB HA CAMBIADO',
'EL USUARIO ES REDIRIGIDO A SITIOS WEB QUE NO HA SELECCIONADO',
'EL NAVEGADOR WEB EMITE NUMEROSOS MENSAJES EMERGENTES',
'EL NAVEGADOR WEB TIENE BARRAS DE HERRAMIENTAS DESCONOCIDAS EN LA PARTE SUPERIOR']).

conocimiento('MALWARE DE SISTEMA',
['EL SISTEMA TRABAJA LENTO',
'EL SISTEMA SE CUELGA O FALLA FRECUENTEMENTE Y DE FORMA IRREGULAR',
'APARECEN ICONOS DESCONOCIDOS EN EL ESCRITORIO',
'EL SISTEMA SE REINICIA',
'APARECEN MENSAJES INUSUALES DE ERROR']).